// Pre-made questions and answers based on Giuseppe's CV
// These will be shown as suggestions and will stream as if generated by LLM

export interface PremadeQA {
  question: string;
  answer: string;
  followUpQuestions: string[];
  category: string;
}

export const premadeQAs: PremadeQA[] = [
  {
    question: "What is Giuseppe's background in AI and Machine Learning?",
    answer: `Giuseppe is an experienced Machine Learning Engineer and MLOps Engineer with a strong foundation in AI agents and automation. Currently working at CountX since November 2025, he specializes in:

**AI Agent Development:**
- Building sophisticated AI agents using LangChain and LangGraph
- Designing and implementing RAG (Retrieval-Augmented Generation) systems
- Creating workflow automations with n8n to enhance productivity across departments

**Technical Expertise:**
- Advanced proficiency in Python, TensorFlow, and PyTorch
- Expertise in developing predictive models for industrial applications
- Strong background in data analytics and deep learning

His unique combination of mechanical engineering knowledge and ML expertise allows him to design and optimize complex systems with seamless AI integration.`,
    followUpQuestions: [
      "Tell me about Giuseppe's RAG system projects",
      "What automation tools does Giuseppe work with?",
      "What are Giuseppe's certifications in ML and cloud?"
    ],
    category: "background"
  },
  {
    question: "Tell me about Giuseppe's professional experience with AI agents and RAG systems",
    answer: `Giuseppe has extensive hands-on experience with cutting-edge AI technologies:

**At CountX (Nov 2025 - Present):**
- Developed and deployed advanced workflow automations using n8n, LangChain, and LangGraph
- Built specialized AI agents and RAG systems to reduce repetitive work across all company departments
- Designed and implemented a robust Retrieval-Augmented Generation (RAG) system that significantly improved accuracy and relevance of AI-generated content for internal knowledge retrieval
- Engineered custom AI agents to manage specific business processes like intelligent document processing and automated customer support triage

**Personal Projects:**
- Created **peppeGPT.com** - a full-stack AI chatbot with autonomous agents using LangGraph for complex multi-step reasoning
- Built an **Agentic RAG on n8n.io** that intelligently routes queries to the best information retrieval method (semantic search, full-document retrieval, or SQL queries)
- Implemented RAG pipeline with Docling for intelligent document processing, integrated with Neo4j knowledge graph

His expertise spans the full lifecycle from design to deployment of production-ready AI systems.`,
    followUpQuestions: [
      "What projects has Giuseppe built with n8n?",
      "Tell me about Giuseppe's peppeGPT.com project",
      "What technologies does Giuseppe use for RAG systems?"
    ],
    category: "ai_experience"
  },
  {
    question: "What data science and ML projects has Giuseppe completed?",
    answer: `Giuseppe has delivered several impressive ML projects showcasing diverse skills:

**Computer Vision:**
- **AI Vehicle Damage Detection System (2025)** - YOLOv8-based system identifying 8 damage types in images & video, with Flask + React/TypeScript web app that cuts claim processing from days to minutes
- **Anomaly Detection App (2024)** - AI-driven quality control system using MVTec dataset to automate defect detection in manufacturing

**Recommender Systems:**
- **Book Recommender App (2025)** - Collaborative filtering system with FastAPI, Airflow pipelines, and DVC-tracked data/models, delivering real-time suggestions in <30ms

**Time Series & Forecasting:**
- **Cryptocurrency Forecasting (2024)** - Real-time crypto dashboard with Prophet & scikit-learn ensembles, FastAPI + WebSockets backend, and React/TypeScript frontend

**Optimization & Engineering:**
- **Genetic Algorithm CAD Optimization (2024)** - Leveraging genetic algorithms to optimize CAD designs in FreeCAD, focusing on structural efficiency while minimizing material usage

All projects feature production-ready deployments with modern MLOps practices, containerization, and comprehensive documentation.`,
    followUpQuestions: [
      "Tell me about Giuseppe's vehicle damage detection system",
      "What is Giuseppe's approach to MLOps and deployment?",
      "How does Giuseppe integrate AI with engineering?"
    ],
    category: "projects"
  },
  {
    question: "What certifications and education does Giuseppe have?",
    answer: `Giuseppe has an impressive educational background combining engineering and data science:

**Recent Education:**
- **Data Science and MLOps** - Université Paris 1 Panthéon-Sorbonne (Sept 2024 - June 2025)
  - Comprehensive training in ML, deep learning, big data, and cloud deployment
  - Focus on MLOps: CI/CD pipelines, Docker, Kubernetes, model deployment, monitoring & scaling
  - n8n automation & orchestration, workflow pipelines, API connections

**Engineering Foundation:**
- **Master of Science in Mechanical Engineering** - INSA Lyon (2010-2015)
  - Major in R&D with focus on advanced simulations and CAD modeling
  - Erasmus semester at RWTH Aachen University
  - Master thesis on optimizing common rail pump systems with EHD simulations

**Certifications:**
- MLOps and Data Science certificates from Datascientest.com
- AWS Cloud Practitioner Essentials
- Microsoft Azure Fundamentals
- Stanford: Machine Learning Specialization
- Google: Advanced Data Analytics Specialization
- IBM: Databases and SQL for Data Science (with Honors)
- CATIA CAD 2D/3D and ANSYS WorkBench FEM
- Udemy: ROS2 Odometry and Control

This combination gives him a unique edge in applying AI to complex engineering problems.`,
    followUpQuestions: [
      "What cloud platforms does Giuseppe work with?",
      "How does Giuseppe combine engineering and ML?",
      "What programming languages does Giuseppe master?"
    ],
    category: "education"
  },
  {
    question: "What technologies and tools does Giuseppe master?",
    answer: `Giuseppe has a comprehensive tech stack spanning ML, MLOps, and engineering:

**Programming & ML:**
- Python (expert level), scikit-learn, TensorFlow, PyTorch
- Pandas, NumPy for data manipulation
- Claude.ai for AI development

**MLOps & Deployment:**
- Docker, Kubernetes (fundamentals)
- CI/CD pipelines, DVC for model versioning
- Model deployment & monitoring

**Pipelines & Orchestration:**
- Apache Airflow for workflow orchestration
- n8n for low-code integration and automation
- ETL/ELT design and data integration
- SQL for database operations

**APIs & Backend:**
- FastAPI, Flask for REST APIs
- WebSockets for real-time communication

**Computer Vision & NLP:**
- YOLOv8, OpenCV for vision projects
- RAG orchestration with n8n
- LangChain, LangGraph for agent development

**Cloud & DevOps:**
- AWS (Cloud Practitioner certified)
- Microsoft Azure (certified)
- Linux, Git/GitHub
- Supabase for backend services

**Engineering Tools:**
- CATIA, FreeCAD for CAD modeling
- ANSYS WorkBench for FEM analysis

This diverse skillset enables him to build end-to-end AI solutions from data processing to production deployment.`,
    followUpQuestions: [
      "What cloud services does Giuseppe prefer for ML deployment?",
      "Tell me about Giuseppe's experience with n8n",
      "How does Giuseppe approach MLOps best practices?"
    ],
    category: "skills"
  },
  {
    question: "Tell me about Giuseppe's work at CountX",
    answer: `At CountX (November 2025 - Present), Giuseppe serves as an AI Agent and Automation Engineer, where he's making significant impact:

**Core Responsibilities:**
- Developing and deploying advanced workflow automations using n8n, LangChain, and LangGraph
- Building specialized agents and RAG systems to enhance productivity and reduce repetitive work across ALL company departments

**Key Achievements:**
- **Designed and implemented a robust RAG system** that significantly improved accuracy and relevance of AI-generated content for internal knowledge retrieval
- **Utilized n8n for low-code integration**, orchestrating complex data flows between cloud services and proprietary APIs to streamline cross-departmental operations
- **Engineered custom AI agents** using LangChain and LangGraph to manage specific business processes:
  - Intelligent document processing
  - Automated customer support triage
  - Cross-functional workflow automation

**Impact:**
The automation solutions have transformed how different departments work, reducing manual effort and improving decision-making through AI-enhanced processes.

This role showcases Giuseppe's ability to apply cutting-edge AI technologies to solve real business problems at scale.`,
    followUpQuestions: [
      "What other companies has Giuseppe worked for?",
      "Tell me about Giuseppe's ERP consulting experience",
      "What industries has Giuseppe worked in?"
    ],
    category: "work_experience"
  },
  {
    question: "What is Giuseppe's experience with ERP and manufacturing?",
    answer: `Giuseppe has strong domain expertise in ERP systems and manufacturing operations:

**At Steltix (Dec 2022 - Jul 2024) - ERP Consultant:**
- Delivered ERP data solutions for manufacturing clients
- Mapped and integrated heterogeneous datasets with SQL to standardize BOM/MRP/DRP and capacity planning data across enterprise systems
- Built repeatable ETL/ELT workflows for materials and production planning
- Improved process visibility and reduced manual reconciliation
- **Contributed to a 20% increase in operational efficiency**
- Partnered with business stakeholders to capture requirements, design data models and roadmaps
- Oversaw routing, manufacturing workflows, and cost accounting data quality

**At IMI Climate Control (Sep 2017 - Jul 2022) - Mechanical Engineer | Data Scientist:**
- Developed data-driven testing platforms in Python to collect, analyze, and visualize sensor data
- **Raised defect detection by 30% and cut testing time by 20%**
- Applied statistical modeling and predictive analytics to identify design/performance issues
- **Improved product reliability while reducing production costs by 10% and enhancing efficiency by 10%**
- Implemented analytics-informed design iterations with CAD prototypes and FEM validation
- Introduced robotic automation to assembly processes, **reducing setup time by 20%**

This experience gives him unique insight into applying AI/ML to real-world industrial challenges.`,
    followUpQuestions: [
      "How does Giuseppe apply AI to manufacturing?",
      "What results has Giuseppe achieved in production environments?",
      "Tell me about Giuseppe's data-driven approach"
    ],
    category: "manufacturing"
  },
  {
    question: "Tell me about Giuseppe's peppeGPT.com project",
    answer: `peppeGPT.com is Giuseppe's showcase full-stack AI chatbot project demonstrating advanced AI engineering:

**Frontend & UX:**
- Built with React, TypeScript, and Shadcn UI
- Real-time streaming responses for smooth user experience
- Multi-modal capabilities for rich interactions

**AI Agent Architecture:**
- Leverages **Pydantic AI** for type-safe agent orchestration
- Built autonomous AI agents using **LangGraph** for complex multi-step reasoning
- Tool orchestration and stateful conversation management with conditional branching logic

**RAG Pipeline:**
- Designed automated workflows with **n8n** for document ingestion pipelines
- **Docling** for intelligent document processing
- Integrated with **Neo4j knowledge graph** for semantic search and contextual retrieval
- Supports PDF, DOCX, and web content

**Backend & Infrastructure:**
- FastAPI for high-performance backend
- Webhook triggers and seamless integration between external services
- Deployed as containerized microservices (Docker Compose) on cloud VPS
- Nginx reverse proxy with SSL encryption
- **Supabase authentication** (Google OAuth)
- Multi-LLM provider support (OpenAI, Ollama, OpenRouter)

This project demonstrates Giuseppe's ability to architect and deploy production-ready AI systems with modern best practices.`,
    followUpQuestions: [
      "What other web projects has Giuseppe built?",
      "How does Giuseppe handle authentication and security?",
      "Tell me about Giuseppe's deployment strategies"
    ],
    category: "projects"
  },
  {
    question: "What languages does Giuseppe speak?",
    answer: `Giuseppe is highly multilingual with impressive language proficiency:

**Native Languages:**
- Italian (Native Speaker)
- Albanian (Native Speaker)

**Advanced Proficiency (C1 Certified):**
- **English** - IELTS, TOEIC certified
- **Spanish** - DELE certified
- **French** - TCF certified

**Fluent (B2 Certified):**
- **German** - TELC certified

**Additional:**
- Portuguese (conversational)

This linguistic versatility is a significant asset in international work environments and demonstrates Giuseppe's commitment to continuous learning. Being able to communicate fluently in 5+ languages enables him to collaborate effectively with global teams and understand diverse markets.

Combined with his technical expertise, this makes him particularly valuable for international projects and multicultural teams in the AI/ML space.`,
    followUpQuestions: [
      "Where has Giuseppe worked internationally?",
      "What countries has Giuseppe studied in?",
      "How does Giuseppe's international experience benefit his work?"
    ],
    category: "languages"
  },
  {
    question: "Tell me about Giuseppe's vehicle damage detection system",
    answer: `The AI Vehicle Damage Detection System (2025) is a sophisticated computer vision project:

**Core Technology:**
- Built with **YOLOv8** for real-time object detection
- Identifies **8 different damage types**: doors, headlights, bumpers, dents, scratches, cracks, broken glass, and paint damage
- Works with both images and video for flexible inspection scenarios

**Application Architecture:**
- **Flask backend** for model serving and API endpoints
- **React + TypeScript** frontend for user-friendly interface
- Responsive design for use on mobile devices during on-site inspections

**Business Impact:**
- **Automates vehicle inspections** that traditionally require human expertise
- **Slashes claim processing time from days to minutes**
- Reduces human error and provides consistent damage assessment
- Generates detailed reports with damage location and severity

**Use Cases:**
- Insurance claim processing
- Car rental check-in/check-out
- Pre-purchase vehicle inspections
- Fleet management and maintenance scheduling

This project showcases Giuseppe's ability to apply deep learning to solve real-world business problems with measurable ROI. The system demonstrates expertise in computer vision, model deployment, and creating production-ready applications.`,
    followUpQuestions: [
      "What other computer vision projects has Giuseppe built?",
      "How does Giuseppe train and optimize ML models?",
      "Tell me about Giuseppe's approach to model deployment"
    ],
    category: "projects"
  },
  {
    question: "How does Giuseppe integrate AI with traditional engineering?",
    answer: `Giuseppe's unique background bridges mechanical engineering and AI, creating powerful synergies:

**Educational Foundation:**
- Master's in Mechanical Engineering from INSA Lyon with R&D focus
- Specialized in CAD modeling (CATIA V5) and FEM analysis (ANSYS Workbench)
- Master thesis on optimizing common rail pump systems using Elastohydrodynamic simulations

**Practical Integration:**

1. **Genetic Algorithm CAD Optimization (2024)**
   - Leveraged genetic algorithms to optimize CAD designs automatically
   - Integrated FreeCAD with Python for automated generative design workflows
   - Focused on improving structural efficiency while minimizing material usage
   - Makes advanced optimization techniques accessible and cost-effective

2. **At IMI Climate Control:**
   - Developed data-driven testing platforms for heating and hydronic systems
   - Combined sensor data analysis with FEM validation (ANSYS)
   - Applied statistical modeling to identify design/performance issues
   - Implemented analytics-informed design iterations with CAD prototypes

3. **Anomaly Detection in Manufacturing:**
   - AI-driven quality control for industrial applications
   - Automated defect detection faster and more accurately than human inspection

**The Advantage:**
This combination allows Giuseppe to:
- Understand the physical constraints and engineering requirements
- Apply AI/ML optimally to engineering problems
- Validate AI solutions with proven engineering methods
- Bridge communication between engineering and data science teams

This interdisciplinary approach is increasingly valuable as industries embrace digital transformation and AI-driven design.`,
    followUpQuestions: [
      "What CAD and simulation tools does Giuseppe use?",
      "Tell me about Giuseppe's optimization projects",
      "How does Giuseppe validate AI models in engineering contexts?"
    ],
    category: "engineering_ai"
  },
  {
    question: "What programming languages does Giuseppe master?",
    answer: `Giuseppe's primary programming expertise is centered on **Python**, which he uses extensively across his work:

**Python Expertise:**
- **Data Science & ML**: Develops models using TensorFlow, PyTorch, scikit-learn
- **Data Manipulation**: Pandas, NumPy for analysis and processing
- **Backend Development**: FastAPI, Flask for REST APIs
- **Automation & Workflows**: Python scripts for workflow automation and ETL/ELT pipelines
- **Engineering Integration**: FreeCAD automation, genetic algorithms, and optimization
- **Testing & Analytics**: Data-driven testing platforms, statistical modeling

**Database & Query Languages:**
- **SQL**: Database operations, ERP data integration, querying and management
  - Mapped and integrated heterogeneous datasets with SQL at Steltix
  - Standardized BOM/MRP/DRP and capacity planning data across enterprise systems

**Web Development:**
- **JavaScript/TypeScript**: Used in frontend development for projects like peppeGPT.com
  - React + TypeScript for user interfaces
  - WebSockets for real-time communication

Giuseppe's programming skills are applied practically across AI/ML development, data engineering, backend services, and full-stack applications. His Python expertise in particular enables him to build end-to-end solutions from data processing and model training to production deployment.`,
    followUpQuestions: [
      "What ML frameworks does Giuseppe prefer?",
      "How does Giuseppe approach backend API development?",
      "Tell me about Giuseppe's data engineering experience"
    ],
    category: "skills"
  }
];

// Function to get a random selection of questions
export const getRandomQuestions = (count: number, exclude: string[] = []): PremadeQA[] => {
  const availableQuestions = premadeQAs.filter(
    qa => !exclude.includes(qa.question)
  );
  
  const shuffled = [...availableQuestions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
};

// Function to find a specific Q&A by question text
export const findQA = (question: string): PremadeQA | undefined => {
  return premadeQAs.find(qa => 
    qa.question.toLowerCase() === question.toLowerCase()
  );
};

// Function to get follow-up questions based on current conversation
export const getContextualFollowUps = (
  lastQuestion: string,
  conversationHistory: string[]
): string[] => {
  const qa = findQA(lastQuestion);
  
  if (qa && qa.followUpQuestions.length > 0) {
    // Filter out questions already asked
    return qa.followUpQuestions.filter(
      q => !conversationHistory.includes(q)
    );
  }
  
  // If no specific follow-ups, return random questions from different categories
  const askedQuestions = conversationHistory;
  const categoriesAsked = new Set(
    conversationHistory
      .map(q => findQA(q)?.category)
      .filter(Boolean)
  );
  
  // Try to get questions from categories not yet explored
  const unexploredQuestions = premadeQAs.filter(
    qa => !categoriesAsked.has(qa.category) && !askedQuestions.includes(qa.question)
  );
  
  if (unexploredQuestions.length > 0) {
    return getRandomQuestions(3, askedQuestions).map(qa => qa.question);
  }
  
  // Otherwise, return any unasked questions
  return getRandomQuestions(3, askedQuestions).map(qa => qa.question);
};

// Simulate streaming text with realistic delays
export const simulateStreaming = async (
  text: string,
  onChunk: (chunk: string) => void,
  initialDelay: number = 2000,
  chunkDelay: number = 30
): Promise<void> => {
  // Initial delay before starting to "type"
  await new Promise(resolve => setTimeout(resolve, initialDelay));
  
  // Split text into words for more natural streaming
  const words = text.split(' ');
  let currentText = '';
  
  for (let i = 0; i < words.length; i++) {
    const word = words[i];
    currentText += (i > 0 ? ' ' : '') + word;
    onChunk(currentText);
    
    // Variable delay based on punctuation for more natural feel
    let delay = chunkDelay;
    if (word.endsWith('.') || word.endsWith('!') || word.endsWith('?')) {
      delay = chunkDelay * 3;
    } else if (word.endsWith(',') || word.endsWith(':') || word.endsWith(';')) {
      delay = chunkDelay * 2;
    }
    
    await new Promise(resolve => setTimeout(resolve, delay));
  }
};
